# -*- coding: utf-8 -*-
"""
===============================================================================
Script: 08a — Future Streamflow Source Partition (Snow / Rain / Wastage)
Author: Dr. Caroline Aubry-Wake
Affiliation: University of Lethbridge
Date: 2025-11-20
Python: 3.9+

Purpose
-------
Compute and visualize future streamflow partitioning by climatic source
(Balanced-derived / Rainfall-derived / Imbalanced-derived) for the Langshisha
basin under SSP1-2.6, SSP3-7.0, and SSP5-8.5.

This script:
    • Reconstructs daily Snow / Rain / Wastage-sourced discharge from SPHY
      ensemble-mean daily flow components.
    • Applies annual glacier wastage fractions derived from ensemble glacier
      mass balance analysis.
    • Computes DOY climatologies for early (2025–2034) and late (2090–2099)
      periods.
    • Computes annual source-based streamflow composition.
    • Exports diagnostic summary statistics.

This script generates the Snow / Rain / Wastage panels used in
Figures 8–9 of the manuscript.

-------------------------------------------------------------------------------
Inputs
-------------------------------------------------------------------------------
SPHY ensemble outputs (future simulations):
    base_dir = "/scratch/depfg/aubry001/out/fut"
        <GCM>/<SSP>/*.tss daily flow component files

Required daily components (.tss):
    - STotDTS.tss  (Snow Off Glacier)
    - GTotDTS.tss  (Snow + Ice On Glacier)
    - RTotDTS.tss  (Rain Off Glacier)
    - BTotRDTS.tss (GW from Rain)
    - BTotSDTS.tss (GW from Snow)
    - BTotGDTS.tss (GW from Glacier)
    - QAllDTS.tss  (Total)

Glacier balance ensemble outputs:
    - ensemble_balance_<ssp>.csv → used to derive annual wastage fraction

Flow component ensemble summaries:
    - FlowComponents_ensemble_<ssp>.csv

Precipitation ensemble summaries:
    - Precip_flux_<ssp>_ENSEMBLE.csv

Basin footprint:
    - footprint.tif (used to compute basin area)

-------------------------------------------------------------------------------
Outputs (saved in out_dir = "/scratch/depfg/aubry001/fig/futlong_summary")
-------------------------------------------------------------------------------

Figures
-------
1. DOY_SourceHydrographs_4panel.png + .pdf

   4-row stacked DOY hydrographs:
       (d) Multi-SSP early period (2025–2034 mean)
       (e) SSP126 late century (2090–2099)
       (f) SSP370 late century (2090–2099)
       (g) SSP585 late century (2090–2099)

2. Annual_Streamflow_Composition_SnowRainWastage.png + .pdf

   3-panel annual stacked composition (one panel per SSP)
   showing Snow / Rain / Wastage contributions over time.

   Units: annual mean discharge (m³ s⁻¹)

Tables
------
3. SourceHydrographs_DOY_stats.csv

   For each SSP and period (Early / Late), and each source:
       - Mean_discharge_m3s
       - Mean_total_m3s
       - Fraction_of_total_%
       - Peak_DOY
       - Peak_date
       
4. Annual_Streamflow_Composition_SnowRainWastage.csv

   Columns:
       - SSP
       - Year
       - Snow (m³ s⁻¹)
       - Rain (m³ s⁻¹)
       - Wastage (m³ s⁻¹)
       - Total (m³ s⁻¹)
       - Frac_Snow
       - Frac_Rain
       - Frac_Wastage
-------------------------------------------------------------------------------
Notes
-------------------------------------------------------------------------------
• Snow includes snowmelt and seasonal glacier melt (non-wastage component).
• Wastage represents the imbalanced (net glacier mass loss) contribution.
• Daily source partitioning uses annual wastage fractions assumed constant
  within each year.
• DOY climatologies exclude Feb 29 (DOY ≤ 365).
• Ensemble means are computed across all available GCMs per SSP.
• Final figure panels are assembled in Inkscape with pathway-based panels
  generated by Script 08b.

===============================================================================
"""
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ternary
from matplotlib.lines import Line2D

# === PATHS (adjust as needed) ===
fig_dir_flow    = "/scratch/depfg/aubry001/fig/futlong_flow"
fig_dir_gw      = "/scratch/depfg/aubry001/fig/futlong_gw"
fig_dir_precip  = "/scratch/depfg/aubry001/fig/futlong_snowrain"
fig_dir_balance = "/scratch/depfg/aubry001/fig/futlong_balance"

out_dir = "/scratch/depfg/aubry001/fig/futlong_summary"
os.makedirs(out_dir, exist_ok=True)

ssps = ["ssp126", "ssp370", "ssp585"]
colors = {"ssp126": "#1f77b4", "ssp370": "#ff7f0e", "ssp585": "#d62728"}

keep_decades = [2030, 2060, 2090]

#-- basin area
import rasterio
import numpy as np

footprintpath = "/scratch/depfg/aubry001/geospatial/Langshisha_basin_outline/footprint.tif"

CELL_SIZE = 20  # meters
CELL_AREA = CELL_SIZE * CELL_SIZE  # m²

with rasterio.open(footprintpath) as src:
    footprint = src.read(1, masked=True)

# Count active (unmasked) cells
n_cells = np.sum(~footprint.mask)

# Basin area
A_BASIN_M2 = n_cells * CELL_AREA
A_BASIN_KM2 = A_BASIN_M2 / 1e6

print(f"Active cells: {n_cells}")
print(f"Basin area: {A_BASIN_M2:.2e} m² ({A_BASIN_KM2:.2f} km²)")


ssps = ["ssp126", "ssp370", "ssp585"]

def read_tss(file_path: str, start_date: pd.Timestamp, colname="col_1") -> pd.Series:
    """Read SPHY .tss file and return the first data column as a Series indexed by datetime."""
    with open(file_path, "r") as f:
        lines = f.readlines()

    start_idx = None
    for i, line in enumerate(lines):
        parts = line.strip().split()
        if len(parts) >= 2 and parts[0].lstrip("-").isdigit():
            start_idx = i
            break
    if start_idx is None:
        raise ValueError(f"No numeric data found in {file_path}")

    df = pd.read_csv(file_path,sep=r"\s+",skiprows=start_idx, header=None, engine="python")
    df.columns = ["day"] + [f"col_{i}" for i in range(1, df.shape[1])]

    t0 = df["day"].iloc[0]
    dt = start_date + pd.to_timedelta(df["day"] - t0, unit="D")
    s = pd.Series(df["col_1"].astype(float).values, index=dt, name=colname).sort_index()
    return s



# -------------------------------
# Load Glacier Wastage Fraction
# -------------------------------
def load_wastage_fraction(ssp):
    """Load annual wastage fraction from ensemble_balance_SSP.csv"""
    path = os.path.join(fig_dir_balance, f"ensemble_balance_{ssp}.csv")
    df = pd.read_csv(path)
    df["year"] = df["year"] if "year" in df.columns else df["year_mean"]
    df = df.set_index("year")
    return df["imbalanced_mm_mean"] / df["total_mm_mean"]

def load_precip_inputs_with_wastage(ssp):
    """
    Panel (a): Input composition in VOLUME units (m3/yr):
      - Snow and Rain: convert basin-mean mm/yr to m3/yr using A_BASIN_M2
      - Wastage: use imbalanced_m3_mean directly from ensemble_balance (already m3/yr)
    """

    # --- Load precip (Snow + Rain, in mm over basin) ---
    path_p = os.path.join(fig_dir_precip, f"Precip_flux_{ssp}_ENSEMBLE.csv")
    dp = pd.read_csv(path_p).rename(columns=lambda x: x.strip())

    dp["Year"] = 2017 + (dp["YearIndex"] - 1)
    dp = dp[["Year", "Snow_mm_mean", "Rain_mm_mean"]]

    # Convert mm -> m3 using basin area
    dp["Snow"] = (dp["Snow_mm_mean"] / 1000.0) * A_BASIN_M2
    dp["Rain"] = (dp["Rain_mm_mean"] / 1000.0) * A_BASIN_M2
    dp = dp[["Year", "Snow", "Rain"]]

    # --- Load wastage as m3/yr from glacier balance ---
    path_w = os.path.join(fig_dir_balance, f"ensemble_balance_{ssp}.csv")
    dw = pd.read_csv(path_w)

    if "year" in dw.columns:
        dw["Year"] = dw["year"]
    elif "year_mean" in dw.columns:
        dw["Year"] = dw["year_mean"]
    else:
        raise ValueError("Cannot find year column in wastage file.")

    # Use *volume* wastage
    if "imbalanced_m3_mean" not in dw.columns:
        raise ValueError("Expected column 'imbalanced_m3_mean' not found in ensemble_balance file.")

    dw = dw[["Year", "imbalanced_m3_mean"]].rename(columns={"imbalanced_m3_mean": "Wastage"})

    # Merge
    df = pd.merge(dp, dw, on="Year", how="left")

    return df  # Year, Snow(m3/yr), Rain(m3/yr), Wastage(m3/yr)


def extract_years(df):
    """
    Try to get a proper Year series from the dataframe.
    Handles:
      - 'Year' column (int)
      - 'datetime' as string dates
      - 'datetime' as plain year numbers (e.g., 2025, 2026)
    """
    if "Year" in df.columns:
        return df["Year"].astype(int)

    if "datetime" in df.columns:
        col = df["datetime"]

        # If it's numeric, assume it's already the year
        if np.issubdtype(col.dtype, np.number):
            return col.astype(int)

        # Otherwise, parse as datetime string
        return pd.to_datetime(col).dt.year

    raise ValueError("No 'Year' or 'datetime' column found to extract years.")


def load_streamflow_gw_only_partition(ssp, wastage_frac):
    path = os.path.join(fig_dir_flow, f"FlowComponents_ensemble_{ssp}.csv")
    df = pd.read_csv(path).rename(columns=lambda x: x.strip())
    years = extract_years(df).astype(int)
    f = wastage_frac.reindex(years).to_numpy()

    gw_snow = df["GW from Snow_m3yr_mean"].to_numpy()
    gw_rain = df["GW from Rain_m3yr_mean"].to_numpy()
    gw_glac = df["GW from Glacier_m3yr_mean"].to_numpy()

    waste_gw = gw_glac * f
    seas_gw  = gw_glac * (1.0 - f)

    BalancedGW = gw_snow + seas_gw
    RainGW     = gw_rain
    ImbalGW    = waste_gw

    return pd.DataFrame({
        "Year": years,
        "Snow": BalancedGW,   # keep naming consistent with ternary code
        "Rain": RainGW,
        "Wastage": ImbalGW
    })
# -------------------------------
# Load Recharge Partition
# -------------------------------
def load_recharge_partition(ssp, wastage_frac):
    path = os.path.join(fig_dir_gw, f"GWre_partition_GlacTable_{ssp}.csv")
    df = pd.read_csv(path).rename(columns=lambda x: x.strip())
    years = extract_years(df)

    snow = df["Snow_GWre_mm_mean"]
    rain = df["Rain_GWre_mm_mean"]
    glac = df["Glacier_GWre_mm_mean"]

    waste = glac * wastage_frac.reindex(years).values
    seas  = glac * (1 - wastage_frac.reindex(years).values)

    return pd.DataFrame({
        "Year": years,
        "Snow": snow + seas,
        "Rain": rain,
        "Wastage": waste
    })

# -------------------------------
# Load Streamflow Components
# -------------------------------

def load_streamflow_partition(ssp, wastage_frac):
    path = os.path.join(fig_dir_flow, f"FlowComponents_ensemble_{ssp}.csv")
    df = pd.read_csv(path).rename(columns=lambda x: x.strip())
    years = extract_years(df).astype(int)
    waste_frac = wastage_frac.reindex(years).to_numpy()

    # Pull mean discharge (m3/s)
    snowoff = df["Snow Off Glacier_m3yr_mean"]
    sice    = df["Snow + Ice On Glacier_m3yr_mean"]
    rainoff = df["Rain Off Glacier_m3yr_mean"]

    gw_snow = df["GW from Snow_m3yr_mean"]
    gw_rain = df["GW from Rain_m3yr_mean"]
    gw_glac = df["GW from Glacier_m3yr_mean"]

    waste_frac = wastage_frac.reindex(years).values
    waste_sice = sice * waste_frac
    seas_sice  = sice * (1 - waste_frac)
    waste_gw   = gw_glac * waste_frac
    seas_gw    = gw_glac * (1 - waste_frac)

    # Categories (still m3/s)
    Snow_q = snowoff + gw_snow  + seas_gw+ seas_sice
    Rain_q = rainoff + gw_rain
    Wast_q = waste_sice + waste_gw

    # Convert to m3/s
    SEC_PER_YR = 365.0 * 24 * 3600 
    Snow = Snow_q / SEC_PER_YR
    Rain = Rain_q / SEC_PER_YR
    Wastage = Wast_q / SEC_PER_YR
    Total_calc = Snow + Rain + Wastage

    # If your ensemble file has total volume:
    if "Total_m3yr_mean" in df.columns:
        Total_file = df["Total_m3yr_mean"].to_numpy()
        rel_err = (Total_calc.to_numpy() - Total_file) / Total_file
        print(ssp, "streamflow closure median rel err:", np.nanmedian(np.abs(rel_err)))

    return pd.DataFrame({"Year": years, "Snow": Snow, "Rain": Rain, "Wastage": Wastage})


# base_dir: folder with subdirs per GCM, each containing <GCM>/<SSP>/FLOW_FILES
base_dir = "/scratch/depfg/aubry001/out/fut"  # <-- adjust

# SPHY TSS component names (daily)
FLOW_FILES = {
    "Snow Off Glacier": "STotDTS.tss",
    "Snow + Ice On Glacier": "GTotDTS.tss",
    "Rain Off Glacier": "RTotDTS.tss",
    "GW from Rain": "BTotRDTS.tss",
    "GW from Snow": "BTotSDTS.tss",
    "GW from Glacier": "BTotGDTS.tss",
    "Total": "QAllDTS.tss",
}

# you already have: ssps, colors, load_wastage_fraction()

early_range = (2025, 2034)
late_range  = (2090, 2099)
start_date = pd.to_datetime("2015-01-01")
# ---- helper: load ensemble-mean daily components for one SSP ----
def load_ensemble_daily_components(ssp):
    """
    For a given SSP, load all GCM daily TSS files for each flow component,
    align them on a common datetime index, and return df_mean:
      index = datetime, columns = FLOW_FILES keys (m3/s, ensemble mean).
    """
    gcm_dirs = [
        d for d in os.listdir(base_dir)
        if os.path.isdir(os.path.join(base_dir, d))
    ]
    if not gcm_dirs:
        raise RuntimeError(f"No GCM directories found in {base_dir}")

    comp_series = {comp: [] for comp in FLOW_FILES.keys()}

    for gcm in gcm_dirs:
        ssp_dir = os.path.join(base_dir, gcm, ssp)
        if not os.path.isdir(ssp_dir):
            continue

        for comp, fname in FLOW_FILES.items():
            tss_path = os.path.join(ssp_dir, fname)
            if not os.path.exists(tss_path):
                print(f"⚠️ Missing {tss_path}, skipping ({gcm}, {ssp}, {comp})")
                continue

            s = read_tss(tss_path, start_date, colname=comp)
            s.name = f"{gcm}_{comp}"
            comp_series[comp].append(s)

    df_mean = pd.DataFrame()
    for comp, series_list in comp_series.items():
        if not series_list:
            continue
        df_all = pd.concat(series_list, axis=1)
        df_mean[comp] = df_all.mean(axis=1)

    df_mean = df_mean.sort_index()
    return df_mean

# ---- helper: daily Snow/Rain/Wastage from daily components + annual f_waste ----
def daily_sources_from_components(df_daily, wastage_frac):
    """
    df_daily: ensemble-mean daily components (FLOW_FILES keys)
    wastage_frac: Series indexed by year with f_waste = wastage / total glacier melt

    Returns DataFrame with daily Snow, Rain, Wastage, Total (m3/s).
    """
    df = df_daily.copy()
    df["Year"] = df.index.year
    df["DOY"]  = df.index.dayofyear

    # map annual wastage fraction to each day
    df["f_waste"] = df["Year"].map(wastage_frac)
    df["f_waste"] = df["f_waste"].fillna(0.0)  # pre-2017 etc.

    f = df["f_waste"].values

    snowoff = df["Snow Off Glacier"]
    sice    = df["Snow + Ice On Glacier"]
    rainoff = df["Rain Off Glacier"]

    gw_snow = df["GW from Snow"]
    gw_rain = df["GW from Rain"]
    gw_glac = df["GW from Glacier"]

    # split glacier components into seasonal vs wastage (constant fraction per year)
    waste_sice = sice * f
    seas_sice  = sice * (1.0 - f)

    waste_gw   = gw_glac * f
    seas_gw    = gw_glac * (1.0 - f)

    Snow     = snowoff + gw_snow + seas_sice + seas_gw
    Rain     = rainoff + gw_rain
    Wastage  = waste_sice + waste_gw
    Total    = Snow + Rain + Wastage  # should closely match df["Total"]

    out = pd.DataFrame({
        "Snow": Snow,
        "Rain": Rain,
        "Wastage": Wastage,
        "Total": Total
    }, index=df.index)

    # keep year & DOY for climatologies
    out["Year"] = df["Year"]
    out["DOY"]  = df["DOY"]
    return out

# ---- helper: DOY climatology for a given period ----
def doy_climatology_sources(df_sources, year_min, year_max):
    df = df_sources.copy()
    mask = (df["Year"] >= year_min) & (df["Year"] <= year_max) & (df["DOY"] <= 365)
    df = df.loc[mask]

    grp = df.groupby("DOY")[["Snow", "Rain", "Wastage", "Total"]].mean()
    grp = grp.reindex(range(1, 366))
    return grp


#%% with 4 panel
# ==========================================================
# DOY hydrographs with source-based (Snow / Rain / Wastage)
# 4-panel layout: Early multi-SSP mean + late-century SSP126,
# SSP370, SSP585
# ==========================================================

base_dir = "/scratch/depfg/aubry001/out/fut"  # <-- as before

FLOW_FILES = {
    "Snow Off Glacier": "STotDTS.tss",
    "Snow + Ice On Glacier": "GTotDTS.tss",
    "Rain Off Glacier": "RTotDTS.tss",
    "GW from Rain": "BTotRDTS.tss",
    "GW from Snow": "BTotSDTS.tss",
    "GW from Glacier": "BTotGDTS.tss",
    "Total": "QAllDTS.tss",
}

early_range = (2025, 2034)
late_range  = (2090, 2099)

# ----------------------------------------------------------
# Helpers (same logic as before)
# ----------------------------------------------------------
def load_ensemble_daily_components(ssp):
    """
    For a given SSP, load all GCM daily TSS files for each flow component,
    align them on a common datetime index, and return df_mean:
        index = datetime, columns = FLOW_FILES keys (m³/s, ensemble mean).
    """
    gcm_dirs = [
        d for d in os.listdir(base_dir)
        if os.path.isdir(os.path.join(base_dir, d))
    ]
    if not gcm_dirs:
        raise RuntimeError(f"No GCM directories found in {base_dir}")

    comp_series = {comp: [] for comp in FLOW_FILES.keys()}

    for gcm in gcm_dirs:
        ssp_dir = os.path.join(base_dir, gcm, ssp)
        if not os.path.isdir(ssp_dir):
            continue

        for comp, fname in FLOW_FILES.items():
            tss_path = os.path.join(ssp_dir, fname)
            if not os.path.exists(tss_path):
                print(f"⚠️ Missing {tss_path}, skipping ({gcm}, {ssp}, {comp})")
                continue

            s = read_tss(tss_path, start_date, colname=comp)
            s.name = f"{gcm}_{comp}"
            comp_series[comp].append(s)

    df_mean = pd.DataFrame()
    for comp, series_list in comp_series.items():
        if not series_list:
            continue
        df_all = pd.concat(series_list, axis=1)
        df_mean[comp] = df_all.mean(axis=1)

    df_mean = df_mean.sort_index()
    return df_mean


def daily_sources_from_components(df_daily, wastage_frac):
    """
    Convert daily SPHY components to daily Snow/Rain/Wastage-sourced discharge.
    wastage_frac: annual fraction (Series indexed by year).
    """
    df = df_daily.copy()
    df["Year"] = df.index.year
    df["DOY"]  = df.index.dayofyear

    # map annual wastage fraction to each day
    df["f_waste"] = df["Year"].map(wastage_frac)
    df["f_waste"] = df["f_waste"].fillna(0.0)

    f = df["f_waste"].values

    snowoff = df["Snow Off Glacier"]
    sice    = df["Snow + Ice On Glacier"]
    rainoff = df["Rain Off Glacier"]

    gw_snow = df["GW from Snow"]
    gw_rain = df["GW from Rain"]
    gw_glac = df["GW from Glacier"]

    # split glacier components
    waste_sice = sice * f
    seas_sice  = sice * (1.0 - f)

    waste_gw   = gw_glac * f
    seas_gw    = gw_glac * (1.0 - f)

    Snow     = snowoff + gw_snow + seas_sice + seas_gw
    Rain     = rainoff + gw_rain
    Wastage  = waste_sice + waste_gw
    Total    = Snow + Rain + Wastage

    out = pd.DataFrame({
        "Snow": Snow,
        "Rain": Rain,
        "Wastage": Wastage,
        "Total": Total,
        "Year": df["Year"],
        "DOY": df["DOY"],
    }, index=df.index)

    return out


def doy_climatology_sources(df_sources, year_min, year_max):
    """
    Mean DOY hydrograph for Snow/Rain/Wastage/Total over the given year range.
    """
    df = df_sources.copy()
    mask = (
        (df["Year"] >= year_min)
        & (df["Year"] <= year_max)
        & (df["DOY"] <= 365)
    )
    df = df.loc[mask]

    grp = df.groupby("DOY")[["Snow", "Rain", "Wastage", "Total"]].mean()
    grp = grp.reindex(range(1, 366))
    return grp

# ----------------------------------------------------------
# Build DOY climatologies for each SSP
# ----------------------------------------------------------
doy_store = {ssp: {"Early": None, "Late": None} for ssp in ssps}

for ssp in ssps:
    print(f"Processing DOY source hydrograph for {ssp}...")
    wfrac_annual = load_wastage_fraction(ssp)        # same function as ternary
    df_daily     = load_ensemble_daily_components(ssp)
    df_sources   = daily_sources_from_components(df_daily, wfrac_annual)

    doy_store[ssp]["Early"] = doy_climatology_sources(df_sources, *early_range)
    doy_store[ssp]["Late"]  = doy_climatology_sources(df_sources, *late_range)

# multi-SSP mean for the early period
early_mean = sum(doy_store[ssp]["Early"] for ssp in ssps) / len(ssps)

# for consistent y-limits
all_clims = [early_mean] + [doy_store[ssp]["Late"] for ssp in ssps]
ymax = max(clim["Total"].max() for clim in all_clims) * 1.05

# ----------------------------------------------------------
# Plot 4-panel (4 rows x 1 column) DOY source hydrographs
# ----------------------------------------------------------
source_colors = {
    "Snow":    "#BFC0C0",  # light grey
    "Rain":    "#1f4e79",  # deep blue
    "Wastage": "#7b3294",  # purple
}

fig, axes = plt.subplots(4, 1, figsize=(3, 8), sharex=True, sharey=True)

panel_info = [
    ("(d) 2025–2034", early_mean),
    ("(e) SSP126, 2090–2099",          doy_store["ssp126"]["Late"]),
    ("(f) SSP370, 2090–2099",          doy_store["ssp370"]["Late"]),
    ("(g) SSP585, 2090–2099",          doy_store["ssp585"]["Late"]),
]

for ax, (label, clim) in zip(axes, panel_info):
    ax.stackplot(
        clim.index.values,
        [clim["Wastage"], clim["Snow"], clim["Rain"]],
        colors=[
            source_colors["Wastage"],
            source_colors["Snow"],
            source_colors["Rain"],
        ],
        alpha=0.9,
    )
    ax.text(0.02, 0.95, label,
            transform=ax.transAxes,
            fontsize=10, va="top", ha="left")
    ax.set_xlim(1, 365)
    ax.set_ylim(0, ymax)
    ax.grid(alpha=0.3)

# axis labels / ticks
axes[-1].set_xlabel("Day of Year")
for ax in axes:
    ax.set_ylabel("Discharge (m³ s⁻¹)")
axes[-1].set_xticks([1, 60, 121, 182, 244, 305, 365])
axes[-1].set_xticklabels(["Jan", "Mar", "May", "Jul", "Sep", "Nov", "Dec"])

# legend
handles = [
    plt.Rectangle((0, 0), 1, 1, color=source_colors["Snow"]),
    plt.Rectangle((0, 0), 1, 1, color=source_colors["Rain"]),
    plt.Rectangle((0, 0), 1, 1, color=source_colors["Wastage"]),
]

labels = ["Balanced-derived", "Rainfall-derived", "Imbalanced-derived"]

fig.legend(
    handles, labels,
    loc="upper center",
    ncol=3,
    bbox_to_anchor=(0.5, 1.02),
    frameon=False,
)

plt.tight_layout()
plt.subplots_adjust(top=0.93)

out_doy = os.path.join(out_dir, "DOY_SourceHydrographs_4panel.png")
out_doy_pdf = os.path.join(out_dir, "DOY_SourceHydrographs_4panel.pdf")

plt.savefig(out_doy, dpi=300, bbox_inches="tight")
plt.savefig(out_doy_pdf, dpi=300, bbox_inches="tight")

plt.show()
print("Saved DOY source hydrograph:", out_doy)

# ==========================================
# Source-based stats (Snow / Rain / Wastage)
# ==========================================

source_stats_rows = []

def compute_source_period_stats(df_sources, year_min, year_max, ssp, period_label):
    """
    df_sources: daily Snow/Rain/Wastage/Total, index=datetime
                (from daily_sources_from_components)
    Computes mean discharge and fraction of total for each source,
    plus the DOY and date of peak contribution, over the given year range.
    """
    df = df_sources.copy()
    df["Year"] = df.index.year
    df["DOY"]  = df.index.dayofyear

    # restrict to requested years and drop Feb 29
    mask = (
        (df["Year"] >= year_min) &
        (df["Year"] <= year_max) &
        (df["DOY"] <= 365)
    )
    df = df.loc[mask]

    sources_to_plot = ["Snow", "Rain", "Wastage"]

    # mean discharge over the period (m³/s)
    mean_total = df["Total"].mean()

    for src in sources_to_plot:
        mean_src = df[src].mean()
        frac_pct = 100.0 * mean_src / mean_total if mean_total > 0 else np.nan

        # peak day and date within the period
        idx_peak  = df[src].idxmax()
        doy_peak  = int(df.loc[idx_peak, "DOY"])
        date_peak = idx_peak.date().isoformat()

        source_stats_rows.append({
            "SSP": ssp,
            "Period": period_label,          # "Early" or "Late"
            "Year_min": year_min,
            "Year_max": year_max,
            "Source": src,
            "Mean_discharge_m3s": mean_src,
            "Mean_total_m3s": mean_total,
            "Fraction_of_total_%": frac_pct,
            "Peak_DOY": doy_peak,
            "Peak_date": date_peak,
        })


# --- loop over SSPs and periods using source-based daily series ---
for ssp in ssps:
    print(f"\nComputing source-based stats for {ssp}...")

    # 1) annual wastage fraction (same as in ternary script)
    wfrac_annual = load_wastage_fraction(ssp)

    # 2) ensemble-mean daily SPHY components
    df_daily = load_ensemble_daily_components(ssp)

    # 3) convert to daily Snow / Rain / Wastage / Total
    df_sources = daily_sources_from_components(df_daily, wfrac_annual)

    # 4) stats for early and late periods
    compute_source_period_stats(df_sources, early_range[0], early_range[1], ssp, "Early")
    compute_source_period_stats(df_sources, late_range[0],  late_range[1],  ssp, "Late")


# --- build table and save to CSV ---
source_stats_df = pd.DataFrame(source_stats_rows)

out_source_stats_csv = os.path.join(out_dir, "SourceHydrographs_DOY_stats.csv")
source_stats_df.to_csv(out_source_stats_csv, index=False)
print(f"\nSaved source-based stats to:\n  {out_source_stats_csv}")


# --- compact console summary (rounded) ---
print("\n=== Mean discharge and % of total by source (Snow / Rain / Wastage) ===")
for ssp in ssps:
    for period in ["Early", "Late"]:
        sub = source_stats_df[
            (source_stats_df["SSP"] == ssp) &
            (source_stats_df["Period"] == period)
        ].copy()
        if sub.empty:
            continue

        print(f"\n-- {ssp.upper()} | {period} "
              f"({int(sub['Year_min'].iloc[0])}-{int(sub['Year_max'].iloc[0])}) --")

        print(
            sub[["Source", "Mean_discharge_m3s",
                 "Fraction_of_total_%", "Peak_DOY", "Peak_date"]]
            .sort_values("Fraction_of_total_%", ascending=False)
            .round({"Mean_discharge_m3s": 3, "Fraction_of_total_%": 1})
            .to_string(index=False)
        )


# %%
# ==========================================================
# Annual streamflow composition: Snow / Rain / Wastage
# ==========================================================

# Rebuild per-year Snow/Rain/Wastage time series for each SSP
stream_yearly_list = []
for ssp in ssps:
    wfrac = load_wastage_fraction(ssp)          # annual f_waste (same as ternary)
    sf = load_streamflow_partition(ssp, wfrac)  # Year, Snow, Rain, Wastage (annual totals or means)
    sf["SSP"] = ssp
    stream_yearly_list.append(sf)

stream_yearly = pd.concat(stream_yearly_list, ignore_index=True)

# sort by year inside each SSP for plotting
stream_yearly = stream_yearly.sort_values(["SSP", "Year"])
# --------------------------------------
# Export annual streamflow composition
# --------------------------------------

stream_yearly_export = stream_yearly.copy()

stream_yearly_export["Total"] = (
    stream_yearly_export["Snow"] +
    stream_yearly_export["Rain"] +
    stream_yearly_export["Wastage"]
)

stream_yearly_export["Frac_Snow"] = (
    stream_yearly_export["Snow"] / stream_yearly_export["Total"]
)
stream_yearly_export["Frac_Rain"] = (
    stream_yearly_export["Rain"] / stream_yearly_export["Total"]
)
stream_yearly_export["Frac_Wastage"] = (
    stream_yearly_export["Wastage"] / stream_yearly_export["Total"]
)

out_csv = os.path.join(
    out_dir,
    "Annual_Streamflow_Composition_SnowRainWastage.csv"
)

stream_yearly_export.to_csv(out_csv, index=False)
print(f"Saved annual composition table: {out_csv}")
# colours for the three source categories
source_colors = {
    "Snow":    "#BFC0C0",  # light grey
    "Rain":    "#1f4e79",  # deep blue
    "Wastage": "#7b3294",  # purple
}


fig, axes = plt.subplots(1, len(ssps), figsize=(10,3), sharey=True)

panel_labels = ["(c)", "(d)", "(e)"]
for col, ssp in enumerate(ssps):
    ax = axes[col]
    sub = stream_yearly[stream_yearly["SSP"] == ssp]

    years    = sub["Year"].values
    wastage  = sub["Wastage"].values
    snow     = sub["Snow"].values
    rain     = sub["Rain"].values
    total_q  = snow + rain + wastage

    # stacked annual contributions
    ax.stackplot(
        years,
        [wastage, snow, rain],
        colors=[source_colors["Wastage"],
                source_colors["Snow"],
                source_colors["Rain"],
                ],
        alpha=0.9
    )

    ax.text(0.02, 0.95, panel_labels[col],
            transform=ax.transAxes,
            ha="left", va="top", fontsize=11)

    ax.set_xlabel("Year")
    if col == 0:
        ax.set_ylabel("Annual streamflow contribution (m³ s⁻¹)")  

    ax.grid(alpha=0.3)
    # keep x-axis limited to the actual data years
    ax.set_xlim(years[0], years[-1])
    ax.margins(x=0)   # no extra padding on x-axis

# one common legend
handles = [
    plt.Rectangle((0, 0), 1, 1, color=source_colors["Snow"]),
    plt.Rectangle((0, 0), 1, 1, color=source_colors["Rain"]),
    plt.Rectangle((0, 0), 1, 1, color=source_colors["Wastage"])
]
labels = ["Balanced-derived", "Rainfall-derived", "Imbalanced-derived", "Total streamflow"]

fig.legend(handles, labels, loc="upper center", ncol=4, frameon=False, bbox_to_anchor=(0.5, 1.01))

plt.tight_layout()
plt.subplots_adjust(top=0.85)

out_annual = os.path.join(out_dir, "Annual_Streamflow_Composition_SnowRainWastage.png")
plt.savefig(out_annual, dpi=300, bbox_inches="tight")
out_annual = os.path.join(out_dir, "Annual_Streamflow_Composition_SnowRainWastage.pdf")
plt.savefig(out_annual, dpi=300, bbox_inches="tight")
plt.show()
print("Saved annual composition figure:", out_annual)

# %%
